---
name: CPAN-Mini-Indexed
version: 0.03_01.2
author:
  - 'Nadim ibn hamouda el Khemir. <nkh@cpan.org>'
abstract: Index the content of your CPAN mini repository
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Tar: 0
  File::Copy: 0
  File::Find::Rule: 0
  File::Temp: 0.21
  Getopt::Long: 0
  IO::Zlib: 0
  Readonly: 0
  Search::Indexer: 0.75
  Sub::Exporter: 0
  Term::Bash::Completion::Generator: 0
  Text::Pluralize: 0
  Time::HiRes: 0
build_requires:
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Warn: 0
  Text::Diff: 0
provides:
  CPAN::Mini::Indexed:
    file: lib/CPAN/Mini/Indexed.pm
    version: 0.03_01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
